name: Scrape GPU

on:
  schedule:
    - cron: '0 9 * * *' # Ejecutar todos los días a las 9:00 AM
  workflow_dispatch:

jobs:
  Scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
        
      - name: Install Dependencies
        run: npm install
          
      - name: Run Script
        env:
          SCRAPER_API: ${{ secrets.SCRAPER_API }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: node index.js
        
      - name: Commit and push to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update GPUs Daatabase 
      


