name: Scrape GPU

on:
  schedule:
    - cron: '0 9 * * *' # Ejecutar todos los días a las 9:00 AM
  workflow_dispatch:

jobs:
  Scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
        
      - name: Install Dependencies
        run: npm install
          
      - name: Run Script
        env:
          SCRAPER_API: ${{ secrets.SCRAPER_API }}
        run: |
          node index.js
          git config user.name scraper-gpu-bot
          git add -A
          git commit -m "[bot] Update GPU Database"
          git push origin main
        
      # - name: Commit and push files
      #   if: always()
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Update output.json  


